name: Build and Deploy Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Builds the documentation website under ./build/html
      - name: Build documentation website
        run: |
          chmod +x ./build_docs.sh
          ./build_docs.sh

      # Deploys the website to the gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html

