name: Build and Deploy Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Builds the documentation website under ./build/html
      - name: Build documentation website
        run: |
          chmod +x ./build_docs.sh
          ./build_docs.sh

      # Deploys the website to the gh-pages branch
      - name: Deploy to GitHub Pages
        # Trigger on push to the default branch (usually 'master' or 'main')
        # as well as if triggered manually with a workspace dispatch event.
        if: ${{ github.ref_name == github.event.repository.default_branch && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html

